namespace Rubrum.Abp.LanguageManagement;

public abstract class LanguageManagementEntityFrameworkCoreTestBase :
    LanguageManagementTestBase<RubrumAbpLanguageManagementEntityFrameworkCoreTestModule>;
